### ISSUE TITLE
Permission denied al hacer CRUD al volumen documents en runner nonroot con Docker

### ISSUE THREAD

**Issue by tnfAngel** [JSPaste/Backend#62]
Los volúmenes de docker suelen ser root, por lo que el usuario nonroot no va a poder hacer operaciones CRUD hacia ellos, como workaround se puede usar el usuario root, pero tiene que haber otra forma de montar los volúmenes en Docker sin necesidad de root para acceder a ellos/modificarlos

![imagen](https://github.com/JSPaste/Backend/assets/57068341/9513115a-77be-4e12-ae96-390776d1472f)

@inetol tu has tenido algún problema de estos con tu instancia?

**Comment by inetol** [comment]
¿Dónde tienes el volumen montado? Cuando Docker monta los volúmenes estos deberían tienen los uid y gid del usuario de la imagen (nonroot), pueden leerse todos los ficheros si eres root (o con un usuario "normal" si le especificas a Docker que use ese uid y gid), pero no está pensado para que sean editados o modificados externamente

**Comment by tnfAngel** [comment]
> ¿Dónde tienes el volumen montado? Cuando Docker monta los volúmenes estos deberían tienen los uid y gid del usuario de la imagen (nonroot), pueden leerse todos los ficheros si eres root (o con un usuario "normal" si le especificas a Docker que use ese uid y gid), pero no está pensado para que sean editados o modificados externamente

No modifiqué el Dockerfile/Containerfile, por lo que debería ser `/home/nonroot/documents`, usé la imagen hosteada en GHCR

 `$ sudo docker volume inspect <id>`, no tiene nada dentro btw
**![imagen](https://github.com/JSPaste/Backend/assets/57068341/7a2bcbde-3990-45e4-9891-2243760a9c2d)**

 No estoy usando la flag --user en el docker run por cierto

**Comment by inetol** [comment]
Puedes probar a especificar --user=65532:65532 al instanciar el contenedor para que Docker lo ejecute con el uid y gid del usuario nonroot y no haya problemas.

**Comment by inetol** [comment]
*Debería especificar el USER en el Containerfile para evitar este inconveniente...*

**Comment by tnfAngel** [comment]
> Puedes probar a especificar --user=65532:65532 para que Docker ejecute el contenedor con el uid y gid del usuario nonroot y no haya problemas.

La cosa es que estoy usando docker-compose, y lo que he intentado sin éxito es establecer el usuario nonroot con la directiva user

Relacionado: https://github.com/docker/compose/issues/3270 (cabe destacar que no estoy poniendo la directiva volume directamente en el docker compose, estoy aprovechando la del Containerfile)

este es mi docker-compose

```yml
version: '3.8'
services:
    # Cloudflare Tunnel Service
    tunnel:
        image: cloudflare/cloudflared
        env_file: .env.cloudflare.prod
        restart: always
        command: tunnel run
        networks:
            - jsp

    backend:
        image: ghcr.io/jspaste/backend:latest
        env_file: .env.backend.prod
        user: nonroot
        restart: always
        networks:
            - jsp

    frontend:
        image: ghcr.io/jspaste/frontend:latest
        env_file: .env.frontend.prod
        restart: always
        networks:
            - jsp

networks:
    jsp:
        external: false

```
